//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public Nullable<int> Cliente_id { get; set; }
        public string Item { get; set; }
        public Nullable<float> Preco { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
